packages:
  - "packages/*"

allowBuilds:
  '@microsoft/m365agentstoolkit-cli': false
  '@mongodb-js/zstd': false
  esbuild: true
  keytar: false
  less: false
  node-liblzma: false
  protobufjs: false
  sharp: false
  workerd: false

catalog:
  "@earendil-works/pi-agent-core": "^0.74.0"
  "@earendil-works/pi-ai": "^0.74.0"
