// Re-export everything from SDK
export {
  AgentContext,
  type AgentContextOptions,
  AgentRuntime,
  API_TYPES,
  addSkill,
  agentMessagesToChatMessages,
  applyProxyToModel,
  buildAuthorizationUrl,
  buildCustomModel,
  buildSkillsPromptSection,
  type ChatMessage,
  type ChatSession,
  createBashTool,
  createEditFileTool,
  createReadTool,
  createSession,
  DEFAULT_MAX_BYTES,
  DEFAULT_MAX_LINES,
  type DescribedCommand,
  defineTool,
  deleteSession,
  deriveStats,
  detectImageMimeType,
  ensureLockdown,
  exchangeOAuthCode,
  extractPartsFromAssistantMessage,
  type FetchProvider,
  type FetchResult,
  fetchWeb,
  formatSize,
  generateId,
  generatePKCE,
  getFileType,
  getInstalledSkills,
  getOrCreateCurrentSession,
  getOrCreateDocumentId,
  getSession,
  getSessionMessageCount,
  getSharedCustomCommands,
  type ImageSearchOptions,
  type ImageSearchProvider,
  type ImageSearchResult,
  listFetchProviders,
  listImageSearchProviders,
  listSearchProviders,
  listSessions,
  loadOAuthCredentials,
  loadPdfDocument,
  loadSavedConfig,
  loadVfsFiles,
  loadWebConfig,
  type MessagePart,
  OAUTH_PROVIDERS,
  type OAuthCredentials,
  type OAuthFlowState,
  type ProviderConfig,
  parseSkillMeta,
  type RuntimeAdapter,
  type RuntimeState,
  refreshOAuthToken,
  removeOAuthCredentials,
  removeSkill,
  renameSession,
  resizeImage,
  type SearchOptions,
  type SearchProvider,
  type SearchResult,
  type SessionStats,
  type SkillInput,
  type SkillMeta,
  type StorageNamespace,
  sandboxedEval,
  saveConfig,
  saveOAuthCredentials,
  saveSession,
  saveVfsFiles,
  saveWebConfig,
  searchImages,
  searchWeb,
  stripEnrichment,
  syncSkillsToVfs,
  THINKING_LEVELS,
  type ThinkingLevel,
  type ToolCallStatus,
  type ToolResult,
  toBase64,
  toolError,
  toolSuccess,
  toolText,
  truncateHead,
  truncateTail,
  type UploadedFile,
  type WebConfig,
  type WebContext,
} from "@office-agents/sdk";
export type {
  AppAdapter,
  ChatTab,
  CustomCommandsResult,
  ToolExtrasProps,
} from "./chat";
export { ChatInterface, FilesPanel, getChatContext } from "./chat";
export { default as ErrorBoundary } from "./chat/error-boundary.svelte";
